version: '3.8'

services:
  java-app:
    build: .
    container_name: spring-dev
    ports:
      - '8082:3000'
    volumes:
      - .:/app # Live code sync
      - ~/.m2:/root/.m2 # Reuse local Maven repo
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    entrypoint: ['/bin/bash', '/app/docker-entrypoint.sh']
